server:
  port: 8002

# 根据dev还是prod切换mysql连接，
# 默认dev
# 需要prod的配置，可以虚拟机参数 -Ddatabase.env=prod
spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456